name: Action di Guevarra
on: 
  push:
jobs: 
  ciao: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "ciao sono una stringa"
      - run: echo "ciao sono una stringa 2"
      - run: python --version
      - run: pip --version
      - run: lsb_release -d
      - run: ls -la 
      - run: pwd
      - run: env
      - uses: actions/checkout@v4 # svolge git clone
        with:
          sparse-checkout: |
            guevarra
      - run: ls -la 
      - uses: actions/setup-python@v5 # equivalente di venv
        with:
          python-version: '3.12.7'
      - run: python --version
      - run: python prova.py
        working-directory: guevarra
      - run: pip install -r requirements.txt
        working-directory: guevarra
      - run: python pythonstartup.py --dataset_path startupdata.csv
        working-directory: guevarra
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: guevarra/logistic_model.joblib

